/** @type {import('next-sitemap').IConfig} */
export default {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://blueboxx.in',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  trailingSlash: false,
  exclude: [
    '/admin',
    '/admin/*',
    '/student',
    '/student/*',
    '/expert',
    '/expert/*',
    '/company',
    '/company/*',
    '/companies/dashboard',
    '/companies/dashboard/*',
    '/companies/applicants',
    '/companies/applicants/*',
    '/companies/applications',
    '/companies/applications/*',
    '/companies/jobs/create',
    '/companies/post-job',
    '/companies/settings',
    '/companies/settings/*',
    '/jobseeker',
    '/jobseeker/*',
    '/intern',
    '/intern/*',
    '/college',
    '/college/*',
    '/colleges/dashboard',
    '/colleges/dashboard/*',
    '/colleges/placements',
    '/colleges/settings',
    '/colleges/students',
    '/cart',
    '/checkout',
    '/payment-failed',
    '/payment-success',
    '/verify-otp',
    '/verification-pending',
    '/pending-approval',
    '/reset-password',
    '/forgot-password',
    '/onboarding',
    '/auth',
    '/book_consultation'
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/admin/',
          '/admin',
          '/student/',
          '/student',
          '/expert/',
          '/expert',
          '/company/',
          '/company',
          '/companies/dashboard/',
          '/companies/applicants/',
          '/companies/applications/',
          '/companies/jobs/create',
          '/companies/post-job',
          '/companies/settings/',
          '/jobseeker/',
          '/jobseeker',
          '/intern/',
          '/intern',
          '/college/',
          '/college',
          '/colleges/dashboard/',
          '/colleges/placements/',
          '/colleges/settings/',
          '/colleges/students/',
          '/cart',
          '/checkout',
          '/payment-failed',
          '/payment-success',
          '/verify-otp',
          '/verification-pending',
          '/pending-approval',
          '/reset-password',
          '/forgot-password',
          '/onboarding',
          '/auth',
          '/api/'
        ]
      }
    ]
  }
};

